### ISSUE TITLE
write EPIPE error on startup

### ISSUE THREAD

**Issue by rektide** [sidorares/dbusfs#1]
Hiya. The install seems to go ok:

```
/npm install
npm http GET https://registry.npmjs.org/fuse4js/0.1.1
npm http GET https://registry.npmjs.org/dbus-native/0.0.5
npm http GET https://registry.npmjs.org/xml2js/0.1.14
npm http 304 https://registry.npmjs.org/fuse4js/0.1.1
npm http 304 https://registry.npmjs.org/dbus-native/0.0.5
npm http 304 https://registry.npmjs.org/xml2js/0.1.14

> fuse4js@0.1.1 install /home/rektide/archive/dbusfs/node_modules/fuse4js
> node-gyp rebuild

npm http GET https://registry.npmjs.org/binary/0.2.0
npm http GET https://registry.npmjs.org/byline/2.0.3
npm http GET https://registry.npmjs.org/abstractsocket/0.0.2
npm http GET https://registry.npmjs.org/sax
npm http GET https://registry.npmjs.org/put/0.0.6
npm http 304 https://registry.npmjs.org/byline/2.0.3
npm http 304 https://registry.npmjs.org/binary/0.2.0
npm http 304 https://registry.npmjs.org/abstractsocket/0.0.2
npm http 304 https://registry.npmjs.org/put/0.0.6
npm http 304 https://registry.npmjs.org/sax
npm http GET https://registry.npmjs.org/buffers
npm http GET https://registry.npmjs.org/exec_stream
npm http GET https://registry.npmjs.org/chainsaw
make: Entering directory `/home/rektide/archive/dbusfs/node_modules/fuse4js/build'
  CXX(target) Release/obj.target/fuse4js/fuse4js.o
npm http 304 https://registry.npmjs.org/chainsaw
npm http 304 https://registry.npmjs.org/buffers
npm http 304 https://registry.npmjs.org/exec_stream
npm http GET https://registry.npmjs.org/traverse
../fuse4js.cc: In function âvoid* f4js_init(fuse_conn_info*)â:
../fuse4js.cc:253:37: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
npm http 304 https://registry.npmjs.org/traverse
  SOLINK_MODULE(target) Release/obj.target/fuse4js.node
  SOLINK_MODULE(target) Release/obj.target/fuse4js.node: Finished
  COPY Release/fuse4js.node
make: Leaving directory `/home/rektide/archive/dbusfs/node_modules/fuse4js/build'
xml2js@0.1.14 node_modules/xml2js
âââ sax@0.4.2

dbus-native@0.0.5 node_modules/dbus-native
âââ byline@2.0.3
âââ put@0.0.6
âââ abstractsocket@0.0.2 (exec_stream@0.0.3)
âââ binary@0.2.0 (buffers@0.1.1, chainsaw@0.1.0)

fuse4js@0.1.1 node_modules/fuse4js
```

Once installed though, execution fails. Any suggestions for debugging tactics here?

```
   47 12-12-22 0:41:44 -0500
   deneb:~/archive/dbusfs/./dbusfs.js /tmp/mnt
Mount point: /tmp/mnt

events.js:66
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: write EPIPE
    at errnoException (net.js:776:11)
    at Object.afterWrite (net.js:594:19)
    at process.startup.processMakeCallback.process._makeCallback (node.js:238:20)

   48 12-12-22 0:42:05 -0500
   deneb:~/archive/dbusfs/
```

**Comment by sidorares** [comment]
1) Try to check if DBUS_SESSION_BUS_ADDRESS env variable is set
2) make sure you have `socat` installed (dbus-native uses it if bus address is abstract unix socket)
